name: Deploy to GAE

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build deployment folder
        uses: actions/setup-node@v3
      - run: | 
          cd api
          npm ci
          npm run build
          cp ../app.yaml build

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          working_directory: api/build
          
