name: Deploy to GAE

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v3
      - name: Build deployment folder
        run: |
          cd api
          npm ci
          npm run build
          cp ../app.yaml build
          ls ./build
          cp ./package.json build
          ls ./build
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          working_directory: api/build
